module.exports={
    BRAND_DETAILS_COLLECTION:'brandcollection',
    CATEGORY_DETAILS_COLLECTION:'category',
    PRODUCTS_DETAILS_COLLECTION:'products',
    USERS_DETAILS_COLLECTION:'users',
    ADMIN_DETAILS_COLLECTION:'admin',
    CART_DETAILS_COLLECTION:'cart',
}