module.exports={
    BRAND_DETAILS_COLLECTION:'brandcollection',
    CATEGORY_DETAILS_COLLECTION:'category',
    PRODUCTS_DETAILS_COLLECTION:'products',
    USERS_DETAILS_COLLECTION:'users',
    ADMIN_DETAILS_COLLECTION:'admin',
    CART_DETAILS_COLLECTION:'cart',
    ORDER_DETAILS_COLLECTION:'order',
    BANNER_DETAILS_COLLECTION:'banner',
    CATEGORYOFFER_DETAILS_COLLECTION:'categoryoffer',
    PRODUCTOFFER_DETAILS_COLLECTION:'productoffer',
    BUYNOW_DETAILS_COLLECTION:'buynow',
    WISHLIST_DETAILS_COLLECTION:'wishlist',
    
}